### ISSUE TITLE
和RN有啥区别呢？RN也支持页面是Native局部是动态的card

### ISSUE THREAD

**Issue by nianzixin** [hellof2e/Wukong#3]

**Comment by rh541250** [comment]
就是基于XML自定义了一套DSL，用来完成RN所做的事情，话说模版数据下发为什么不考虑json或者protobuf。UI层面的动态化框架有挺多的，维护到后面，大多变成了屎山，牵一发而动全身，😓

**Comment by ArchLL** [comment]
@rh541250 模版数据是json格式。使用XML格式进行样式编写是为了提升编写效率、代码可维护性，发布样式时脚本会自动将xml文件转换为json格式并进行数据压缩。

**Comment by ArchLL** [comment]
每种跨平台方案都有自身的优点和缺点，实际工作中可以选用适合自己项目的技术方案。我简单介绍下Wukong相比RN的优点：1.包体积更小；2.渲染速度更快；3.定制化程度更高；4.环境配置简单，上手更快；5.跨平台能力更强（不仅支持iOS和Android，还支持Flutter\H5\小程序，只是目前这三个平台的代码没有开源）；

**Comment by ArchLL** [comment]
每种跨平台方案都有自身的优点和缺点，实际工作中可以选用适合自己项目的技术方案。
我简单介绍下Wukong相比RN的优点：
1. 包体积更小；
2. 渲染速度更快；
3. 定制化程度更高；
4. 环境配置简单，上手更快；
5. 跨平台能力更强（不仅支持iOS和Android，还支持Flutter\H5\小程序，只是目前这三个平台的代码没有开源）；
